name = "background"
main = "src/index.js"
compatibility_date = "2022-05-31"

workers_dev = true

[[kv_namespaces]]
binding = "KV"
id = "e17874d81437470288b9b3d0ff6dddfa" 
preview_id = "e4a44b464a324c4c8cc7f4e41ad72a52"
